apiVersion: v1
kind: Secret
metadata:
  name: xiangyli-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJlR2xoYm1kNWJHazZTVGx5TkhkV05HcFpZVGgxYVdSRVJYRjNXSGxwUWxsUFJESlVXREpvVkdGSlJVZFFPSEF3UXpjMVlUbFdlU3RQUjJneFptOW9lVzFQZWpsNWFqUjRaUT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
